### ISSUE TITLE
Need to change the hotkey of the menu item for setting the battle speed on the battlefield

### ISSUE THREAD

**Issue by Reotor** [grannypron/PoR_L10n#113] opened 2021-07-19 17:03 UTC
Need to change the hotkey of the menu item for setting the battle speed on the battlefield.

![tempo4](https://user-images.githubusercontent.com/77742895/126198561-c5f07f40-c614-46e0-b207-48f7087857f3.jpg)

Ы (S) ---> Б (,)

_If it is not possible to set this letter as a hotkey, let it remain as it is._

**Comment by grannypron** [comment] 2021-09-15 00:01
Yeah I looked at this one.  The problem is that the Б is mapped to "," and the game only makes capital letters the hotkeys in the game menu and there is no capital comma :/   Actually no menu options that start with Б will work.  If there's another word whose first character maps to a latin letter we can switch it though.  Imma close this one, but just reopen it if we want to change it.

**Closed as completed by grannypron** 2021-09-15 00:01 UTC
